baseurl      = "http://iamyavar.tech/"
title        = "I am Yavar!"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Hi, I am Yavar. The geek you might have heard of! "

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/yavarkhodadadi/"
[[params.social]]
  name = "twitter"
  url = "https://www.linkedin.com/in/yavarkhodadadi/"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Tech blogs by Yavar!"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
       logoText = "Hello! I am Yavar"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/aboutme"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"


[deployment]
[[deployment.targets]]
name = "iamyavar.tech"
URL = "s3://iamyavar.tech?region=us-east-1"

